## .fill_(),.long(),.float(),.view(),.backward(),.unsqueeze(0),.expand(,),.normal(),.numpy(),.contiguous(),.permute()

## from_numpy(),transpose(x,0,1),index_select(x,dim=1,index=indices),cat([x,x],dim=0),stack([x,x])

## mm(x1,x2),bmm,nonzero(a)

## requires_grad

In [9]:
A=[1,2,3]
torch.tensor(A,dtype=torch.int64).size()

torch.Size([3])

In [2]:
def describe(x):
    print("Type:{}".format(x.type()))
    print("Shape/size:{}".format(x.shape))
    print("Values:\n{}".format(x))

In [3]:
import torch
describe(torch.Tensor(2,3))

Type:torch.FloatTensor
Shape/size:torch.Size([2, 3])
Values:
tensor([[5.2667e-08, 1.0073e-11, 1.0980e-05],
        [1.3223e+22, 1.3590e+22, 6.4526e-07]])


In [4]:
A=torch.Tensor(2,3)
A.sum(dim=1)

tensor([6.6753e-07, 2.7059e+23])

In [3]:
describe(torch.rand(2,3))
describe(torch.randn(2,3))

Type:torch.FloatTensor
Shape/size:torch.Size([2, 3])
Values:
tensor([[0.4480, 0.2256, 0.3049],
        [0.8133, 0.7780, 0.1899]])
Type:torch.FloatTensor
Shape/size:torch.Size([2, 3])
Values:
tensor([[ 0.4815,  0.2783, -0.4446],
        [ 0.2815, -1.1861,  0.8423]])


In [4]:
describe(torch.zeros(2,3))
x=torch.ones(2,3)
describe(x)
x.fill_(5)
describe(x)

Type:torch.FloatTensor
Shape/size:torch.Size([2, 3])
Values:
tensor([[0., 0., 0.],
        [0., 0., 0.]])
Type:torch.FloatTensor
Shape/size:torch.Size([2, 3])
Values:
tensor([[1., 1., 1.],
        [1., 1., 1.]])
Type:torch.FloatTensor
Shape/size:torch.Size([2, 3])
Values:
tensor([[5., 5., 5.],
        [5., 5., 5.]])


In [5]:
x=torch.Tensor([[1,2,3],[4,5,6]])
describe(x)

Type:torch.FloatTensor
Shape/size:torch.Size([2, 3])
Values:
tensor([[1., 2., 3.],
        [4., 5., 6.]])


In [6]:
import torch
import numpy as np
npy=np.random.rand(2,3)
describe(torch.from_numpy(npy))

Type:torch.DoubleTensor
Shape/size:torch.Size([2, 3])
Values:
tensor([[0.1246, 0.8605, 0.9945],
        [0.7054, 0.2652, 0.2845]], dtype=torch.float64)


## Tensor 型別與大小

In [3]:
x=torch.FloatTensor([[1,2,3],[4,5,6]])
describe(x)

Type:torch.FloatTensor
Shape/size:torch.Size([2, 3])
Values:
tensor([[1., 2., 3.],
        [4., 5., 6.]])


In [4]:
x=x.long()
describe(x)

Type:torch.LongTensor
Shape/size:torch.Size([2, 3])
Values:
tensor([[1, 2, 3],
        [4, 5, 6]])


In [5]:
x=torch.tensor([[1,2,3],[4,5,6]],dtype=torch.int64)
describe(x)

Type:torch.LongTensor
Shape/size:torch.Size([2, 3])
Values:
tensor([[1, 2, 3],
        [4, 5, 6]])


In [6]:
x=x.float()
describe(x)

Type:torch.FloatTensor
Shape/size:torch.Size([2, 3])
Values:
tensor([[1., 2., 3.],
        [4., 5., 6.]])


## Tensor運算

In [7]:
import torch
x=torch.randn(2,3)
describe(x)

Type:torch.FloatTensor
Shape/size:torch.Size([2, 3])
Values:
tensor([[ 0.6536,  0.6660,  1.4758],
        [-2.6013, -1.2644,  0.7608]])


In [8]:
describe(torch.add(x,x))
describe(x+x)

Type:torch.FloatTensor
Shape/size:torch.Size([2, 3])
Values:
tensor([[ 1.3072,  1.3319,  2.9516],
        [-5.2026, -2.5288,  1.5217]])
Type:torch.FloatTensor
Shape/size:torch.Size([2, 3])
Values:
tensor([[ 1.3072,  1.3319,  2.9516],
        [-5.2026, -2.5288,  1.5217]])


In [9]:
import torch
x=torch.arange(6)
describe(x)

Type:torch.LongTensor
Shape/size:torch.Size([6])
Values:
tensor([0, 1, 2, 3, 4, 5])


In [10]:
x=x.view(2,3)
describe(x)

Type:torch.LongTensor
Shape/size:torch.Size([2, 3])
Values:
tensor([[0, 1, 2],
        [3, 4, 5]])


In [11]:
describe(torch.sum(x,dim=0))

Type:torch.LongTensor
Shape/size:torch.Size([3])
Values:
tensor([3, 5, 7])


In [12]:
describe(torch.sum(x,dim=1))

Type:torch.LongTensor
Shape/size:torch.Size([2])
Values:
tensor([ 3, 12])


In [13]:
describe(torch.transpose(x,0,1))

Type:torch.LongTensor
Shape/size:torch.Size([3, 2])
Values:
tensor([[0, 3],
        [1, 4],
        [2, 5]])


## 索引,分割,連結

In [14]:
import torch
x=torch.arange(6).view(2,3)
describe(x)

Type:torch.LongTensor
Shape/size:torch.Size([2, 3])
Values:
tensor([[0, 1, 2],
        [3, 4, 5]])


In [15]:
describe(x[:1,:2])

Type:torch.LongTensor
Shape/size:torch.Size([1, 2])
Values:
tensor([[0, 1]])


In [16]:
describe(x[0,1])

Type:torch.LongTensor
Shape/size:torch.Size([])
Values:
1


In [17]:
indices=torch.LongTensor([0,2])
describe(torch.index_select(x,dim=1,index=indices))

Type:torch.LongTensor
Shape/size:torch.Size([2, 2])
Values:
tensor([[0, 2],
        [3, 5]])


In [18]:
indices=torch.LongTensor([0,0])
describe(torch.index_select(x,dim=0,index=indices))

Type:torch.LongTensor
Shape/size:torch.Size([2, 3])
Values:
tensor([[0, 1, 2],
        [0, 1, 2]])


In [19]:
row_indices=torch.arange(2).long()
col_indices=torch.LongTensor([0,1])
describe(x[row_indices,col_indices])

Type:torch.LongTensor
Shape/size:torch.Size([2])
Values:
tensor([0, 4])


In [20]:
import torch
x=torch.arange(6).view(2,3)
describe(x)

Type:torch.LongTensor
Shape/size:torch.Size([2, 3])
Values:
tensor([[0, 1, 2],
        [3, 4, 5]])


In [13]:
y=torch.tensor([3,4,2,3,1,1]).view(2,3)

In [19]:
((y==1)).sum()/((x==1)).sum()

tensor(2)

In [21]:
describe(torch.cat([x,x],dim=0))

Type:torch.LongTensor
Shape/size:torch.Size([4, 3])
Values:
tensor([[0, 1, 2],
        [3, 4, 5],
        [0, 1, 2],
        [3, 4, 5]])


In [22]:
describe(torch.cat([x,x],dim=1))

Type:torch.LongTensor
Shape/size:torch.Size([2, 6])
Values:
tensor([[0, 1, 2, 0, 1, 2],
        [3, 4, 5, 3, 4, 5]])


In [23]:
describe(torch.stack([x,x]))

Type:torch.LongTensor
Shape/size:torch.Size([2, 2, 3])
Values:
tensor([[[0, 1, 2],
         [3, 4, 5]],

        [[0, 1, 2],
         [3, 4, 5]]])


In [24]:
import torch
x1=torch.arange(6).view(2,3)
describe(x1)

Type:torch.LongTensor
Shape/size:torch.Size([2, 3])
Values:
tensor([[0, 1, 2],
        [3, 4, 5]])


In [25]:
x2=torch.ones(3,2).long()
x2[:,1]+=1
describe(x2)

Type:torch.LongTensor
Shape/size:torch.Size([3, 2])
Values:
tensor([[1, 2],
        [1, 2],
        [1, 2]])


In [26]:
describe(torch.mm(x1,x2))

Type:torch.LongTensor
Shape/size:torch.Size([2, 2])
Values:
tensor([[ 3,  6],
        [12, 24]])


## Tensor與計算圖

In [27]:
import torch
x=torch.ones(2,2,requires_grad=True)
describe(x)
print(x.grad is None)

Type:torch.FloatTensor
Shape/size:torch.Size([2, 2])
Values:
tensor([[1., 1.],
        [1., 1.]], requires_grad=True)
True


In [28]:
y=(x+2)*(x+5)+3
describe(y)
print(x.grad is None)

Type:torch.FloatTensor
Shape/size:torch.Size([2, 2])
Values:
tensor([[21., 21.],
        [21., 21.]], grad_fn=<AddBackward0>)
True


In [29]:
z=y.mean()
describe(z)
z.backward()
print(x.grad is None)

Type:torch.FloatTensor
Shape/size:torch.Size([])
Values:
21.0
False


In [30]:
a=torch.rand(3,3)
a.unsqueeze(0)

tensor([[[0.1126, 0.7227, 0.6909],
         [0.6635, 0.2150, 0.6473],
         [0.3176, 0.6909, 0.6333]]])

In [31]:
a.squeeze(0)

tensor([[0.1126, 0.7227, 0.6909],
        [0.6635, 0.2150, 0.6473],
        [0.3176, 0.6909, 0.6333]])

In [32]:
3+torch.rand(5,3)*(7-3)

tensor([[3.8128, 6.2206, 4.5460],
        [4.3970, 6.9605, 4.2742],
        [6.8109, 6.4587, 6.4391],
        [6.2851, 5.7137, 5.4023],
        [5.8741, 4.5819, 4.1603]])

In [33]:
a=torch.rand(3,3)
a.normal_()

tensor([[-0.2730, -0.5458, -0.2501],
        [ 0.9238,  1.0297, -1.6009],
        [-1.6546, -0.1617, -0.1970]])

In [34]:
a=torch.Tensor([1,1,1,0,1])
torch.nonzero(a)

tensor([[0],
        [1],
        [2],
        [4]])

In [35]:
a=torch.rand(3,1)
a.expand(3,4)

tensor([[0.6951, 0.6951, 0.6951, 0.6951],
        [0.8642, 0.8642, 0.8642, 0.8642],
        [0.8379, 0.8379, 0.8379, 0.8379]])

In [36]:
a=torch.rand(3,4,5)
b=torch.rand(3,5,4)
torch.bmm(a,b)

tensor([[[1.4301, 0.9451, 1.0600, 1.5926],
         [1.5597, 0.9545, 1.1655, 1.7303],
         [1.5806, 1.1331, 1.2085, 1.7583],
         [1.0857, 0.6336, 0.4580, 0.5606]],

        [[1.3643, 0.8595, 1.3712, 1.2323],
         [1.3397, 0.9657, 0.6508, 1.2114],
         [1.1140, 0.8182, 1.1764, 1.1131],
         [0.9179, 0.9914, 1.2524, 1.0733]],

        [[1.3364, 1.7965, 1.1201, 2.3123],
         [0.6703, 1.4982, 0.9502, 1.5454],
         [1.3488, 1.3315, 1.1379, 1.7896],
         [1.2892, 1.6475, 1.2654, 1.8021]]])

In [46]:
a=torch.rand(3,4,5)
b=torch.rand(5,4)
torch.bmm(a,b.unsqueeze(0).expand(a.size(0),*b.size()))

tensor([[[1.7157, 1.4849, 1.8531, 0.8161],
         [1.6023, 1.5416, 1.9345, 1.3543],
         [1.3108, 1.0001, 1.6143, 0.7118],
         [1.8368, 1.5409, 1.7715, 0.9982]],

        [[1.8503, 1.6244, 2.0250, 1.2856],
         [1.2530, 1.3813, 1.1731, 1.1327],
         [2.2990, 1.8158, 2.3485, 1.2469],
         [1.5958, 1.1853, 1.4865, 0.9404]],

        [[2.0850, 1.8239, 2.0588, 1.2912],
         [1.3238, 1.1143, 1.4832, 0.6712],
         [1.8104, 2.1730, 1.9448, 1.7055],
         [1.5159, 1.3943, 1.5151, 1.1169]]])

## 有關GPU

In [6]:
import torch
print(torch.cuda.is_available())

True


In [7]:
device=torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(device)

cuda


In [8]:
x=torch.rand(3,3).to(device)
describe(x)

Type:torch.cuda.FloatTensor
Shape/size:torch.Size([3, 3])
Values:
tensor([[0.4715, 0.8828, 0.9312],
        [0.2369, 0.6752, 0.3843],
        [0.5574, 0.2572, 0.7077]], device='cuda:0')


In [9]:
y=torch.rand(3,3)
y=y.to(device)
x=x.to(device)
x+y

tensor([[0.4906, 1.3577, 1.1900],
        [0.7675, 0.7226, 0.9550],
        [0.7073, 0.3038, 1.0967]], device='cuda:0')

In [14]:
y=torch.rand(5,5,3,4)
y

tensor([[[[0.8873, 0.4944, 0.8361, 0.8123],
          [0.7058, 0.1809, 0.2613, 0.0824],
          [0.5104, 0.7123, 0.2593, 0.0148]],

         [[0.9145, 0.9262, 0.4924, 0.4946],
          [0.8307, 0.9302, 0.3808, 0.1065],
          [0.2990, 0.5528, 0.1578, 0.7066]],

         [[0.6432, 0.5695, 0.3529, 0.0088],
          [0.0309, 0.3995, 0.6750, 0.3616],
          [0.6826, 0.1056, 0.3685, 0.7887]],

         [[0.5139, 0.7185, 0.7161, 0.5685],
          [0.8651, 0.9674, 0.1884, 0.2715],
          [0.9995, 0.0730, 0.2376, 0.8453]],

         [[0.8213, 0.4602, 0.9654, 0.9442],
          [0.6876, 0.8349, 0.6183, 0.2183],
          [0.0408, 0.5850, 0.7794, 0.1172]]],


        [[[0.4763, 0.5754, 0.8293, 0.9658],
          [0.2120, 0.4575, 0.5060, 0.9136],
          [0.8457, 0.2878, 0.6509, 0.2870]],

         [[0.9480, 0.8410, 0.0976, 0.5111],
          [0.1258, 0.9688, 0.8113, 0.2860],
          [0.0797, 0.6098, 0.4989, 0.3472]],

         [[0.1854, 0.6659, 0.5012, 0.0588],
          [0.411

In [29]:
import torch
a=torch.rand(3,3,8)
a

tensor([[[0.0185, 0.9205, 0.9843, 0.5200, 0.5473, 0.8604, 0.0037, 0.9774],
         [0.7082, 0.9775, 0.5964, 0.1449, 0.5874, 0.6741, 0.4653, 0.3032],
         [0.4966, 0.0043, 0.3996, 0.2425, 0.0210, 0.4053, 0.9795, 0.8877]],

        [[0.3523, 0.4768, 0.9129, 0.9653, 0.8644, 0.7460, 0.4783, 0.9804],
         [0.8750, 0.2690, 0.8995, 0.4015, 0.9703, 0.1822, 0.5932, 0.8068],
         [0.4539, 0.1623, 0.6051, 0.2200, 0.1055, 0.3073, 0.5754, 0.7047]],

        [[0.6778, 0.1845, 0.5507, 0.5501, 0.0550, 0.7640, 0.2336, 0.5152],
         [0.7951, 0.3902, 0.1986, 0.4353, 0.0383, 0.5453, 0.7487, 0.8095],
         [0.6205, 0.1449, 0.8160, 0.0837, 0.5002, 0.6948, 0.2654, 0.3107]]])

In [30]:
a.unsqueeze(dim=0)

tensor([[[[0.0185, 0.9205, 0.9843, 0.5200, 0.5473, 0.8604, 0.0037, 0.9774],
          [0.7082, 0.9775, 0.5964, 0.1449, 0.5874, 0.6741, 0.4653, 0.3032],
          [0.4966, 0.0043, 0.3996, 0.2425, 0.0210, 0.4053, 0.9795, 0.8877]],

         [[0.3523, 0.4768, 0.9129, 0.9653, 0.8644, 0.7460, 0.4783, 0.9804],
          [0.8750, 0.2690, 0.8995, 0.4015, 0.9703, 0.1822, 0.5932, 0.8068],
          [0.4539, 0.1623, 0.6051, 0.2200, 0.1055, 0.3073, 0.5754, 0.7047]],

         [[0.6778, 0.1845, 0.5507, 0.5501, 0.0550, 0.7640, 0.2336, 0.5152],
          [0.7951, 0.3902, 0.1986, 0.4353, 0.0383, 0.5453, 0.7487, 0.8095],
          [0.6205, 0.1449, 0.8160, 0.0837, 0.5002, 0.6948, 0.2654, 0.3107]]]])

In [34]:
a.unsqueeze(dim=3)

tensor([[[[0.0185],
          [0.9205],
          [0.9843],
          [0.5200],
          [0.5473],
          [0.8604],
          [0.0037],
          [0.9774]],

         [[0.7082],
          [0.9775],
          [0.5964],
          [0.1449],
          [0.5874],
          [0.6741],
          [0.4653],
          [0.3032]],

         [[0.4966],
          [0.0043],
          [0.3996],
          [0.2425],
          [0.0210],
          [0.4053],
          [0.9795],
          [0.8877]]],


        [[[0.3523],
          [0.4768],
          [0.9129],
          [0.9653],
          [0.8644],
          [0.7460],
          [0.4783],
          [0.9804]],

         [[0.8750],
          [0.2690],
          [0.8995],
          [0.4015],
          [0.9703],
          [0.1822],
          [0.5932],
          [0.8068]],

         [[0.4539],
          [0.1623],
          [0.6051],
          [0.2200],
          [0.1055],
          [0.3073],
          [0.5754],
          [0.7047]]],


        [[[0.6778],
    

In [39]:
a.squeeze(dim=2)

tensor([[[0.6227, 0.6143, 0.6792, 0.9629, 0.5225, 0.9249, 0.0619, 0.4824],
         [0.6321, 0.8067, 0.1858, 0.1211, 0.3020, 0.7902, 0.2976, 0.4969],
         [0.9965, 0.6426, 0.0581, 0.8401, 0.7206, 0.6755, 0.1569, 0.8246]],

        [[0.7037, 0.1444, 0.7436, 0.4309, 0.9936, 0.2187, 0.7969, 0.9642],
         [0.6359, 0.2568, 0.1521, 0.7960, 0.9417, 0.3796, 0.6397, 0.5824],
         [0.2211, 0.8625, 0.8481, 0.4654, 0.6392, 0.0025, 0.8847, 0.1952]],

        [[0.0163, 0.3288, 0.1753, 0.4239, 0.0590, 0.8536, 0.5102, 0.6103],
         [0.9820, 0.8534, 0.2411, 0.0888, 0.4143, 0.0849, 0.6444, 0.5742],
         [0.9733, 0.9654, 0.4396, 0.0926, 0.7326, 0.6572, 0.5830, 0.5717]]])